CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    brand VARCHAR(2000),
    category_path JSONB NOT NULL DEFAULT '[]'::jsonb,
    image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE merchant_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    merchant VARCHAR(64) NOT NULL,
    external_id VARCHAR(200) NOT NULL,
    product_url VARCHAR(2048) NOT NULL,
    last_collected_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_merchant_products_merchant_external_id UNIQUE (merchant, external_id)
);

CREATE INDEX idx_merchant_products_product_id
    ON merchant_products(product_id);

CREATE INDEX idx_merchant_products_last_collected_at
    ON merchant_products(last_collected_at DESC);

CREATE TABLE offer_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_product_id BIGINT NOT NULL REFERENCES merchant_products(id) ON DELETE CASCADE,
    request_id VARCHAR(128) NOT NULL,
    price_amount BIGINT,
    currency VARCHAR(3),
    shipping_fee_amount BIGINT,
    shipping_fee_currency VARCHAR(3),
    shipping_summary VARCHAR(2000),
    stock_status VARCHAR(32) NOT NULL,
    rating NUMERIC(3, 2),
    review_count INTEGER,
    source_url VARCHAR(2048) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    collector_version VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_offer_snapshots_price_amount
        CHECK (price_amount IS NULL OR price_amount >= 0),
    CONSTRAINT ck_offer_snapshots_shipping_fee_amount
        CHECK (shipping_fee_amount IS NULL OR shipping_fee_amount >= 0),
    CONSTRAINT ck_offer_snapshots_rating
        CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5)),
    CONSTRAINT ck_offer_snapshots_review_count
        CHECK (review_count IS NULL OR review_count >= 0)
);

CREATE INDEX idx_offer_snapshots_merchant_product_collected
    ON offer_snapshots(merchant_product_id, collected_at DESC, id DESC);

CREATE TABLE product_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_snapshot_id BIGINT NOT NULL REFERENCES offer_snapshots(id) ON DELETE CASCADE,
    external_id VARCHAR(200),
    label VARCHAR(300) NOT NULL,
    size VARCHAR(2000),
    color VARCHAR(2000),
    stock_status VARCHAR(32) NOT NULL,
    price_amount BIGINT,
    currency VARCHAR(3),
    source_url VARCHAR(2048) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    collector_version VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_product_options_price_amount
        CHECK (price_amount IS NULL OR price_amount >= 0)
);

CREATE INDEX idx_product_options_offer_snapshot_id
    ON product_options(offer_snapshot_id);

CREATE TABLE evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_product_id BIGINT NOT NULL REFERENCES merchant_products(id) ON DELETE CASCADE,
    offer_snapshot_id BIGINT REFERENCES offer_snapshots(id) ON DELETE CASCADE,
    evidence_type VARCHAR(50) NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    collector_version VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_evidence_merchant_product_id
    ON evidence(merchant_product_id);

CREATE INDEX idx_evidence_offer_snapshot_id
    ON evidence(offer_snapshot_id);
