CREATE TABLE product_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_product_id BIGINT NOT NULL REFERENCES merchant_products(id) ON DELETE CASCADE,
    offer_snapshot_id BIGINT NOT NULL REFERENCES offer_snapshots(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL,
    compared_fields JSONB NOT NULL DEFAULT '[]'::jsonb,
    differences JSONB NOT NULL DEFAULT '[]'::jsonb,
    json_source_url VARCHAR(2048) NOT NULL,
    html_source_url VARCHAR(2048) NOT NULL,
    verified_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_product_verifications_status CHECK (
        status IN ('PENDING', 'MATCHED', 'MISMATCH', 'MISSING_IN_HTML', 'MISSING_IN_JSON', 'FAILED')
    )
);

CREATE INDEX idx_product_verifications_merchant_product
    ON product_verifications(merchant_product_id, verified_at DESC);

CREATE INDEX idx_product_verifications_status
    ON product_verifications(status);
